package frc.robot.util;

/**
 * Estimates ball flight time as a function of distance and launch angle.
 *
 * For each (distance, angle) pair, physics determines a unique launch velocity
 * that lands the ball in the hub center. This means flight time is purely a
 * function of distance and angle — no need to parameterize on velocity.
 *
 * Coefficients were generated by pyshooter's find_velocity_for_target_hit()
 * across the robot's operating range, then fit with a bivariate cubic.
 *   - Distance:  5-21 ft (1.524-6.401 m)
 *   - Angle:     20-60° (limited by hub geometry at close range)
 *   - Ball:      FUEL ~215g, 5.91" diameter, 3000 RPM backspin
 *   - Hub:       1.83m height, 1.06m opening, require descending entry
 *
 * Bivariate cubic polynomial (10 terms):
 *   t = C0 + C1*d + C2*a + C3*d² + C4*d*a + C5*a² + C6*d³ + C7*d²*a + C8*d*a² + C9*a³
 *   (d = distance in meters, a = launch angle in degrees, t = flight time in seconds)
 *
 * RMSE vs simulation: ~14.6 ms, Max error: ~48 ms
 */
public class FlightTimeEstimator {

    // Bivariate cubic coefficients (from pyshooter generate_flight_time_fit.py)
    private static final double C0 = -1.68577655760496e+00;
    private static final double C1 = 4.26333540174406e-01;
    private static final double C2 = 7.16458933510613e-02;
    private static final double C3 = -4.72096749623141e-02;
    private static final double C4 = -3.27451486687655e-03;
    private static final double C5 = -1.22937690727120e-03;
    private static final double C6 = 2.69158500461188e-03;
    private static final double C7 = 1.59521361272250e-05;
    private static final double C8 = 5.30295889324267e-05;
    private static final double C9 = 8.54299286640048e-06;

    private static final double MIN_DISTANCE_METERS = 1.5240;  // 5 ft
    private static final double MAX_DISTANCE_METERS = 6.4008;  // 21 ft
    private static final double MIN_ANGLE_DEGREES = 20.0;
    private static final double MAX_ANGLE_DEGREES = 60.0;
    private static final double MIN_FLIGHT_TIME_SECONDS = 0.05;

    private FlightTimeEstimator() {
    }

    /**
     * Estimate ball flight time from launcher to target.
     *
     * @param distanceMeters horizontal distance to target in meters
     * @param angleDegrees   launch angle above horizontal in degrees
     * @return estimated flight time in seconds (inputs clamped to operating range)
     */
    public static double getFlightTimeSeconds(double distanceMeters, double angleDegrees) {
        double d = Math.max(MIN_DISTANCE_METERS, Math.min(MAX_DISTANCE_METERS, distanceMeters));
        double a = Math.max(MIN_ANGLE_DEGREES, Math.min(MAX_ANGLE_DEGREES, angleDegrees));

        double t = C0
                + C1 * d
                + C2 * a
                + C3 * d * d
                + C4 * d * a
                + C5 * a * a
                + C6 * d * d * d
                + C7 * d * d * a
                + C8 * d * a * a
                + C9 * a * a * a;

        // Clamp to a physical minimum — the polynomial can go negative at
        // short range + low angle where no simulation data exists.
        return Math.max(MIN_FLIGHT_TIME_SECONDS, t);
    }

    public static double getMinDistanceMeters() {
        return MIN_DISTANCE_METERS;
    }

    public static double getMaxDistanceMeters() {
        return MAX_DISTANCE_METERS;
    }

    public static double getMinAngleDegrees() {
        return MIN_ANGLE_DEGREES;
    }

    public static double getMaxAngleDegrees() {
        return MAX_ANGLE_DEGREES;
    }
}
